/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author paulz
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    
    private Gestor gestor;
    
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            gestor = new Gestor();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AdministrarTagJL = new javax.swing.JLabel();
        AdministrarIconoJL = new javax.swing.JLabel();
        SalirIconoJL = new javax.swing.JLabel();
        SalirTagJL = new javax.swing.JLabel();
        CreditosJL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú");

        jPanel1.setBackground(new java.awt.Color(244, 244, 244));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel3.setText("<html><p><span style=\"color: #ffffff;\">Bienvenido, root</span></p>");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 40, 240, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/biblioteca.jpg"))); // NOI18N
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 640, 100);

        AdministrarTagJL.setBackground(new java.awt.Color(153, 51, 255));
        AdministrarTagJL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        AdministrarTagJL.setText("<html><p style=\"text-align: center;\"><span style=\"color: #ffffff;\">Administrar biblioteca</span></p>");
        AdministrarTagJL.setOpaque(true);
        AdministrarTagJL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdministrarTagJLMouseClicked(evt);
            }
        });
        jPanel1.add(AdministrarTagJL);
        AdministrarTagJL.setBounds(150, 250, 100, 60);

        AdministrarIconoJL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/lib.png"))); // NOI18N
        AdministrarIconoJL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255), 2));
        AdministrarIconoJL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdministrarIconoJLMouseClicked(evt);
            }
        });
        jPanel1.add(AdministrarIconoJL);
        AdministrarIconoJL.setBounds(150, 140, 100, 110);

        SalirIconoJL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/exit.png"))); // NOI18N
        SalirIconoJL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255), 2));
        SalirIconoJL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirIconoJLMouseClicked(evt);
            }
        });
        jPanel1.add(SalirIconoJL);
        SalirIconoJL.setBounds(340, 140, 100, 110);

        SalirTagJL.setBackground(new java.awt.Color(153, 51, 255));
        SalirTagJL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        SalirTagJL.setText("<html><p style=\"text-align: center;\"><span style=\"text-align: center; color: #ffffff;\">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Salir</span></p>");
        SalirTagJL.setOpaque(true);
        SalirTagJL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirTagJLMouseClicked(evt);
            }
        });
        jPanel1.add(SalirTagJL);
        SalirTagJL.setBounds(340, 250, 100, 60);

        CreditosJL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        CreditosJL.setForeground(new java.awt.Color(153, 51, 255));
        CreditosJL.setText("Créditos");
        CreditosJL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreditosJLMouseClicked(evt);
            }
        });
        jPanel1.add(CreditosJL);
        CreditosJL.setBounds(20, 360, 60, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdministrarIconoJLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdministrarIconoJLMouseClicked
        gestor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AdministrarIconoJLMouseClicked

    private void AdministrarTagJLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdministrarTagJLMouseClicked
        gestor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AdministrarTagJLMouseClicked

    private void SalirIconoJLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirIconoJLMouseClicked
        System.exit(0);
    }//GEN-LAST:event_SalirIconoJLMouseClicked

    private void SalirTagJLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirTagJLMouseClicked
        System.exit(0);
    }//GEN-LAST:event_SalirTagJLMouseClicked

    private void CreditosJLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreditosJLMouseClicked
        Creditos creditos = new Creditos();
        creditos.setVisible(true);
    }//GEN-LAST:event_CreditosJLMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdministrarIconoJL;
    private javax.swing.JLabel AdministrarTagJL;
    private javax.swing.JLabel CreditosJL;
    private javax.swing.JLabel SalirIconoJL;
    private javax.swing.JLabel SalirTagJL;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
